AugwaShortUrl_API_Create:
    path: '/short-url'
    defaults:
        _controller: 'AugwaShortUrlBundle:ShortUrl:create'
        format: .json
    methods:
        - POST
    requirements:
        format: (.json|.xml|.yml|)

AugwaShortUrl_API_Read:
    path: '/short-url/{code}'
    defaults:
        _controller: 'AugwaShortUrlBundle:ShortUrl:read'
        format: .json
    methods:
        - GET
    requirements:
        format: (.json|.xml|.yml|)
        code: [a-zA-Z0-9]

AugwaShortUrl_API_Update:
    path: '/short-url/{code}'
    defaults:
        _controller: 'AugwaShortUrlBundle:ShortUrl:update'
        format: .json
    methods:
        - PUT
    requirements:
        format: (.json|.xml|.yml|)
        code: [a-zA-Z0-9]

AugwaShortUrl_API_Delete:
    path: '/short-url/{code}'
    defaults:
        _controller: 'AugwaShortUrlBundle:ShortUrl:delete'
        format: .json
    methods:
        - DELETE
    requirements:
        format: (.json|.xml|.yml|)
        code: [a-zA-Z0-9]

AugwaShortUrl_API_List:
    path: '/short-url'
    defaults:
        _controller: 'AugwaShortUrlBundle:ShortUrl:list'
        format: .json
    methods:
        - GET
    requirements:
        format: (.json|.xml|.yml|)

AugwaShortUrl_API_Stats_Read:
    path: '/short-url/{code}/stats'
    defaults:
        _controller: 'AugwaShortUrlBundle:ShortUrl:stats'
        format: .json
    methods:
        - GET
    requirements:
        format: (.json|.xml|.yml|)