Augwa\ShortUrlBundle\Document\User:
    fields:
        userId:
            type: id
            id: true
        emailAddress:
            type: string
            unique: true
        password:
            type: string
        salt:
            type: string
        ipAddress:
            type: int
        dateCreated:
            type: timestamp