AugwaShortUrl_View_Home:
    path: '/'
    defaults:
        _controller: 'AugwaShortUrlBundle:View:home'
    methods:
        - GET

AugwaShortUrl_ShortUrl_Code:
    path: '/{url_code}'
    defaults:
        _controller: 'AugwaShortUrlBundle:View:redirect'
    methods:
        - GET
    requirements:
        url_code: '^[a-zA-Z0-9]+$'