AugwaShortUrl_View_Home:
    path: '/'
    defaults:
        _controller: 'AugwaShortUrlBundle:View:home'
    methods:
        - GET

AugwaShortUrl_ShortUrl_Code:
    path: '/{code}'
    defaults:
        _controller: 'AugwaShortUrlBundle:ShortUrl:redirect'
    methods:
        - GET
    requirements:
        code: [a-zA-Z0-9]