AugwaAPI_Url_Stat_Read:
    path: /url/{url_code}/stats
    defaults:
        _controller: 'AugwaAPIBundle:UrlStat:read'
    methods:
        - GET
    requirements:
        url_code: '^[a-zA-Z0-9]+$'
